mode: train
debug: False

components:
  data: train
  transform: vm
  system: vm_big
  model: vm_big

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.00001

trainer:
  epochs: 250
  warmup_epochs: 10